池化层类似激活函数

In [5]:
import torch
from torch import nn
from d2l import torch as d2l

In [6]:
from numpy import mean


def pool2d(X, pool_size, mode= 'max'):
    p_h, p_w = pool_size
    Y = torch.zeros((X.shape[0] - p_h + 1, X.shape[1] - p_w + 1))

    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode == 'max':
                Y[i, j] = X[i:i + p_h, j:j + p_w].max()
            elif mode == 'avg':
                Y[i, j] = X[i:i + p_h, j:j + p_w].mean()

    return Y

In [7]:
X = torch.arange(0, 9).reshape(3, 3)
print(pool2d(X, (2, 2)))

tensor([[4., 5.],
        [7., 8.]])


In [8]:
X = torch.arange(0, 16, dtype= torch.float32).reshape((1, 1, 4, 4))
print(X)

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])


In [11]:
pool2d = nn.MaxPool2d(2) # 步幅默认和池化窗口大小相同
print(pool2d(X))

tensor([[[[ 5.,  7.],
          [13., 15.]]]])


In [12]:
# 池化层在每个通道上单独运算

X = torch.cat((X, X + 1), 1)
print(pool2d(X))

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])
