多输入多输出通道

In [12]:
import torch
from torch import nn
from d2l import torch as d2l

In [13]:
# 多个通道的输入

def corr2d_multi_in(X, K):
    result = 0
    for x, k in zip(X, K):
        result += d2l.corr2d(x, k)

    return result

In [14]:
X = torch.tensor([[[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]],
               [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]])
K = torch.tensor([[[0.0, 1.0], [2.0, 3.0]], [[1.0, 2.0], [3.0, 4.0]]])

print(corr2d_multi_in(X, K))

tensor([[ 56.,  72.],
        [104., 120.]])


In [15]:
# 多个通道的输出

def corr2d_multi_in_out(X, K):
    # 注意这里的K和上面的K不一样
    return torch.stack([corr2d_multi_in(X, k) for k in K], 0)

K = torch.stack((K, K+1, K+2), 0)

print(corr2d_multi_in_out(X, K))

tensor([[[ 56.,  72.],
         [104., 120.]],

        [[ 76., 100.],
         [148., 172.]],

        [[ 96., 128.],
         [192., 224.]]])


In [17]:
# 1×1卷积相当于全连接层

def corr2d_multi_in_out_1x1(X, K):
    c_i, h, w = X.shape
    c_o = K.shape[0]
    X = X.reshape(c_i, h*w)
    K = K.reshape(c_o, c_i)
    Y = torch.matmul(K, X)
    return Y.reshape(c_o, h, w)

X = torch.normal(0, 1, size= (3, 3, 3))
K = torch.normal(0, 1, size= (2, 3, 1, 1))

Y1 = corr2d_multi_in_out_1x1(X, K)
Y2 = corr2d_multi_in_out(X, K)

print(Y1)
print(Y2)
print(Y1 == Y2)

tensor([[[-1.4519, -2.6334,  1.1745],
         [ 0.1339,  1.4623,  1.7615],
         [ 0.5339,  0.1121, -1.1393]],

        [[ 2.4513,  0.8055, -0.3168],
         [ 0.6248,  0.7546,  1.5512],
         [-1.4694, -0.7371,  1.3451]]])
tensor([[[-1.4519, -2.6334,  1.1745],
         [ 0.1339,  1.4623,  1.7615],
         [ 0.5339,  0.1121, -1.1393]],

        [[ 2.4513,  0.8055, -0.3168],
         [ 0.6248,  0.7546,  1.5512],
         [-1.4694, -0.7371,  1.3451]]])
tensor([[[True, True, True],
         [True, True, True],
         [True, True, True]],

        [[True, True, True],
         [True, True, True],
         [True, True, True]]])
